### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by jibriss** [qpautrat/reactjs-php-bundle#4]
Currently, if any error occurs, the lib _var_dump_s it then _die()_.
Can you please add a better error handling system ?

**Comment by qpautrat** [comment]
:+1:

**Comment by qpautrat** [comment]
The ErrorHandler is called only in `executeJS()` and this fucntion is already called in [constructor](https://github.com/reactjs/react-php-v8js/blob/master/ReactJS.php#L65).
Besides, there is no way to set library source. Neither the app source.
So setting the ErrorHandler is properly useless.

Is it planned to improve this class ? cc @zpao ?

If not i think it would be great to add feature ourself in 2.0.0.

**Comment by zpao** [comment]
@qpautrat We have no plans to make further changes to this code. If you would like to contribute, then we would gladly accept changes.
